[project]
name = "scytdlp"
version = "0.0.1"
description = "Structured archival of SoundCloud likes and reposts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "yt-dlp>=2025.9.5",
]
